# Generated by Django 5.0.1 on 2024-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('contact_number_1', models.CharField(max_length=20)),
                ('contact_number_2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('github_url', models.URLField()),
                ('overview', models.TextField()),
                ('work_experiences', models.ManyToManyField(to='portfolio.workexperience')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
