# Generated by Django 5.0.1 on 2024-02-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_achievement_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=20),
        ),
    ]
