# Generated by Django 5.0.1 on 2024-01-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_achievement_education_skill_profile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
