# Generated by Django 5.0.1 on 2024-01-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_workexperience_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(to='portfolio.education'),
        ),
    ]
