# Generated by Django 5.0.1 on 2024-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(to='portfolio.projects'),
        ),
    ]
