name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server
        run: |
          rsync -e "ssh -i /home/kanye/Downloads/myportfolio_key.pem -o StrictHostKeyChecking=no" -avz /home/kanye/workspace/project_django/myportfolio/ myportfolio@${{ secrets.SERVER}}:/home/myportfolio/myportfolio/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
        
      - name: Debug
        run: |
          echo "Debugging info"
          echo "SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}"
          echo "SERVER: ${{secrets.SERVER }}"

